/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class openmpnativematrix_multiply */

#ifndef _Included_openmpnativematrix_multiply
#define _Included_openmpnativematrix_multiply
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     openmpnativematrix_multiply
 * Method:    generateArray
 * Signature: ([III)V
 */
JNIEXPORT void JNICALL Java_openmpnativematrix_1multiply_generateArray
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     openmpnativematrix_multiply
 * Method:    matrixMultiply
 * Signature: ([III[III[I)V
 */
JNIEXPORT void JNICALL Java_openmpnativematrix_1multiply_matrixMultiply
  (JNIEnv *, jclass, jintArray, jint, jint, jintArray, jint, jint, jintArray);

/*
 * Class:     openmpnativematrix_multiply
 * Method:    printReduce
 * Signature: ([III)V
 */
JNIEXPORT void JNICALL Java_openmpnativematrix_1multiply_printReduce
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
