/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nativeloop */

#ifndef _Included_nativeloop
#define _Included_nativeloop
#ifdef __cplusplus
extern "C" {
#endif
#undef nativeloop_SIZE
#define nativeloop_SIZE 1000000L
#undef nativeloop_ITER
#define nativeloop_ITER 10000L
/*
 * Class:     nativeloop
 * Method:    nmult
 * Signature: ([I[DD)V
 */
JNIEXPORT void JNICALL Java_nativeloop_nmult
  (JNIEnv *, jclass, jintArray, jdoubleArray, jdouble);

#ifdef __cplusplus
}
#endif
#endif
